name: 'action-play'
description: 'Test typescript base action'
author: 'Eduard Tita'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'hexagon'
  color: 'blue'

# Define your inputs here.
inputs:
  name:
    description: 'Your input name here'
    required: true
    default: 'Gaga'

# Define your outputs here.
outputs:
  greeting:
    description: 'Your greeting message'

runs:
  using: node20
  main: dist/index.js
