name: 'action-play'
description: 'Test typescript base action'
author: 'Eduard Tita'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'hexagon'
  color: 'blue'

# Define your inputs here.
inputs:
  name:
    description: 'Your input name here'
    required: true
    default: 'Gaga'

# Define your outputs here.
outputs:
  greeting:
    description: 'Your greeting message'
    value: ${{ steps.inner-action.outputs.greeting }}

#runs:
#  using: node20
#  main: dist/index.js

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Print java version
      id: print-java-version
      run: java -version
      shell: bash

    - name: 'Run script'
      id: inner-action
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
